------soru 1-----
SELECT MODELI FROM BEYAZESYA WHERE TURKODU=1
SELECT COUNT() FROM BEYAZESYA WHERE MARKAKODU=1
SELECT TURADI FROM TURLER WHERE TURKODU = (SELECT TURKODU FROM BEYAZESYA WHERE FIYATI = (SELECT MAX(FIYATI) FROM BEYAZESYA))
SELECT ULKE FROM MARKALAR GROUP BY ULKE HAVING COUNT(ULKE) < 2 ORDER BY ULKE 
SELECT URUNNO FROM BEYAZESYA WHERE TURKODU IN (SELECT TURKODU FROM TURLER WHERE TURADI LIKE 'B%')
SELECT MARKAKODU, AVG(FIYATI) FROM BEYAZESYA GROUP BY MARKAKODU
